# Site settings
title: Home 
email: sina.aghli@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Sina received his M.S. degree in Mechatronics Engineering from University of Tabriz
 in 2012 and currently he is a Ph.D. student in University of Colorado Boulder in the
 field of computer science and is working on developing estimation and control 
 techniques for autonomous cars and in general mobile robots.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: sina.aghli
github_username:  sinaaghli

# Build settings
markdown: kramdown
